#
# SPDX-License-Identifier: Apache-2.0
#

name: PDO CI
on: [pull_request, push]
jobs:
    pdo_ci:
        name: PDO CI Job
        runs-on: ubuntu-22.04

        steps:
            - name: Check out repo
              uses: actions/checkout@v4
              with:
                submodules: recursive
                fetch-depth: 0
                fetch-tags: true

            - name: Display branch name
              run: |
                echo "Building branch $GITHUB_HEAD_REF"
                echo PDO VERSION is $(bin/get_version)
