#
# SPDX-License-Identifier: Apache-2.0
#

name: Build and Push PDO Docker Images

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  DOCKER_REGISTRY: 'ghcr.io'
  PDO_INTERPRETER: wawaka
  PDO_LOG_LEVEL: warning

jobs:
  build_pdo_docker:
    name: Build PDO Images
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Display branch name
        run: |
          echo "Building branch images for $GITHUB_HEAD_REF"
          echo PDO VERSION is $(bin/get_version)
          echo "PDO_VERSION=$(bin/get_version)" >> $GITHUB_ENV

      - name: Build Docker Images
        run: |
          git checkout -b ci-test-branch
          . build/common-config.sh
          make -C docker

      - name: Login to the $DOCKER_REGISTRY Container Registry
        uses: docker/login-action@v2
        with:
          registry: $DOCKER_REGISTRY
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push the images
        run: |
          for image in pdo_services pdo_ccf pdo_client
          do
            docker image tag $DOCKER_REGISTRY/{{ github.repository_owner }}/$image:$PDO_VERSION
            docker image tag $DOCKER_REGISTRY/{{ github.repository_owner }}/$image:latest
            docker image push --all-tags $DOCKER_REGISTRY/{{ github.repository_owner }}/$image
          done
